[metadata]
name = qin-llm-wiki
version = 1.1.0
description = A privacy-safe, AI-first Obsidian project memory architecture
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
python_requires = >=3.9
include_package_data = True

[options.entry_points]
console_scripts =
    qin-llm-wiki = qin_llm_wiki.cli:main

[options.package_data]
qin_llm_wiki =
    templates/vault/*
    templates/vault/*/*
    templates/vault/*/*/*
    templates/vault/*/*/*/*
